### ISSUE TITLE
panic in yubikey crate

### ISSUE THREAD

**Issue by ngortheone** [str4d/age-plugin-yubikey#114] opened 2023-01-28 08:12 UTC
## Environment

* OS: FreeBSD-14
* age-plugin-yubikey version:
freshly installed with cargo install
```
age-plugin-yubikey --version
age-plugin-yubikey 0.3.2
```
## What happened

```
» age-plugin-yubikey --generate
thread 'main' panicked at 'range end index 4 out of range for slice of length 0',
/home/ngor/.local/cargo/registry/src/github.com-1ecc6299db9ec823/yubikey-0.5.0/src/transaction.rs:160:9
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

**Comment by ngortheone** [comment] 2023-01-28 08:23
The error goes away if I update yubikey dependency to
1e02f135f027716d4f155152b6a68e002b948097
https://github.com/iqlusioninc/yubikey.rs/commit/1e02f135f027716d4f155152b6a68e002b948097

i.e. most recent commit in main

**Comment by str4d** [comment] 2023-01-30 00:49
This is a duplicate of #84; see conversation there (and links therein) for more details.

**Closed by str4d** 2023-01-30 00:49 UTC
